import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { AppButton } from 'src/components/Button/App'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <AppButton>Test Button</AppButton>
        <h1 className='text-3xl font-bold underline'>Hello world!</h1>
      </main>
    </div>
  )
}

export default Home
