import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { AppButton } from 'src/components/Button/App'
import { KanbanBoard } from 'src/modules/KanbanBoard'
import { AppFlatButton } from 'src/components/Button/Flat'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <KanbanBoard />
        <AppFlatButton>abc</AppFlatButton>
      </main>
    </div>
  )
}

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale)),
      // Will be passed to the page component as props
    },
  }
}
export default Home
